<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../VibeCheck.Data/VibeCheck.Data.csproj" />
    <None Include="../../VibeCheck.Data/Seed/words.json" Link="Seed/words.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../VibeCheck.Data/Seed/wordinflections.json" Link="Seed/wordinflections.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
