// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibeCheck.Data.Data;

#nullable disable

namespace VibeCheck.Data.Migrations
{
    [DbContext(typeof(VibeCheckDbContext))]
    [Migration("20260903164943_AddQuestionWord")]
    partial class AddQuestionWord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Difficulty", b =>
                {
                    b.Property<int>("DifficultyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DifficultyID"));

                    b.Property<string>("DifficultyDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DifficultyID");

                    b.HasIndex("DifficultyDesc")
                        .IsUnique();

                    b.ToTable("Difficulties");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Meaning", b =>
                {
                    b.Property<int>("MeaningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeaningID"));

                    b.Property<string>("MeaningText")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MeaningID");

                    b.HasIndex("MeaningText")
                        .IsUnique();

                    b.ToTable("Meanings");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int?>("CorrectAlternativeID")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyID")
                        .HasColumnType("int");

                    b.Property<string>("QuestionDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionTypeID")
                        .HasColumnType("int");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("CorrectAlternativeID");

                    b.HasIndex("DifficultyID");

                    b.HasIndex("QuestionTypeID");

                    b.HasIndex("WordID");

                    b.HasIndex("QuestionID", "CorrectAlternativeID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuestionAlternative", b =>
                {
                    b.Property<int>("AlternativeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlternativeID"));

                    b.Property<string>("AlternativeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("AlternativeID");

                    b.HasIndex("QuestionID", "AlternativeID")
                        .IsUnique();

                    b.ToTable("QuestionAlternatives");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QuestionTypeID");

                    b.HasIndex("TypeText")
                        .IsUnique();

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizID"));

                    b.Property<int>("DifficultyID")
                        .HasColumnType("int");

                    b.Property<string>("QuizDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QuizID");

                    b.HasIndex("DifficultyID");

                    b.HasIndex("QuizName")
                        .IsUnique();

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptID"));

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<bool?>("QuizPassed")
                        .HasColumnType("bit");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptID");

                    b.HasIndex("QuizID");

                    b.HasIndex("UserID");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuizAttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptAnswerID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("QuizAttemptID")
                        .HasColumnType("int");

                    b.Property<int>("SelectedAlternativeID")
                        .HasColumnType("int");

                    b.HasKey("AttemptAnswerID");

                    b.HasIndex("QuestionID", "SelectedAlternativeID");

                    b.HasIndex("QuizAttemptID", "QuestionID")
                        .IsUnique();

                    b.ToTable("QuizAttemptAnswers");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuizQuestion", b =>
                {
                    b.Property<int>("QuizQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizQuestionID"));

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("QuizQuestionID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("QuizID", "QuestionID")
                        .IsUnique();

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TagID");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Word", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordID"));

                    b.Property<int>("MeaningID")
                        .HasColumnType("int");

                    b.Property<string>("WordDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WordID");

                    b.HasIndex("MeaningID");

                    b.HasIndex("WordDesc")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.WordExample", b =>
                {
                    b.Property<int>("ExampleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExampleID"));

                    b.Property<string>("ExampleText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("ExampleID");

                    b.HasIndex("WordID");

                    b.ToTable("WordExamples");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.WordTag", b =>
                {
                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("WordID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("WordTags");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.WordVote", b =>
                {
                    b.Property<int>("WordVoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordVoteID"));

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("WordVoteID");

                    b.HasIndex("WordID");

                    b.HasIndex("UserID", "WordID")
                        .IsUnique();

                    b.ToTable("WordVotes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Question", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.QuestionAlternative", "CorrectAlternative")
                        .WithMany()
                        .HasForeignKey("CorrectAlternativeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VibeCheck.Data.Models.Difficulty", "Difficulty")
                        .WithMany("Questions")
                        .HasForeignKey("DifficultyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.Word", "Word")
                        .WithMany("Questions")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.QuestionAlternative", null)
                        .WithMany()
                        .HasForeignKey("QuestionID", "CorrectAlternativeID")
                        .HasPrincipalKey("QuestionID", "AlternativeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CorrectAlternative");

                    b.Navigation("Difficulty");

                    b.Navigation("QuestionType");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuestionAlternative", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Question", "Question")
                        .WithMany("QuestionAlternatives")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Quiz", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Difficulty", "Difficulty")
                        .WithMany("Quizzes")
                        .HasForeignKey("DifficultyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuizAttempt", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuizAttemptAnswer", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Question", "Question")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizAttemptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.QuestionAlternative", "SelectedAlternative")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuestionID", "SelectedAlternativeID")
                        .HasPrincipalKey("QuestionID", "AlternativeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");

                    b.Navigation("SelectedAlternative");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuizQuestion", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Question", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Word", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Meaning", "Meaning")
                        .WithMany("Words")
                        .HasForeignKey("MeaningID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meaning");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.WordExample", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Word", "Word")
                        .WithMany("WordExamples")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.WordTag", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.Tag", "Tag")
                        .WithMany("WordTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.Word", "Word")
                        .WithMany("WordTags")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.WordVote", b =>
                {
                    b.HasOne("VibeCheck.Data.Models.User", "User")
                        .WithMany("WordVotes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Data.Models.Word", "Word")
                        .WithMany("WordVotes")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Difficulty", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Meaning", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Question", b =>
                {
                    b.Navigation("QuestionAlternatives");

                    b.Navigation("QuizAttemptAnswers");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuestionAlternative", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Quiz", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.QuizAttempt", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Tag", b =>
                {
                    b.Navigation("WordTags");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.User", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("WordVotes");
                });

            modelBuilder.Entity("VibeCheck.Data.Models.Word", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("WordExamples");

                    b.Navigation("WordTags");

                    b.Navigation("WordVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
